### ISSUE TITLE
no method named `enable` found for type `()` in the current scope

### ISSUE THREAD

**Issue by GrahamBest** [Jascha-N/minhook-rs#3]
Hey, trying to do

```
let mut test = minhook::Hook::<fn(f32, *mut UserCmd) -> bool>::create::<fn(f32, *mut UserCmd) -> bool>(hook, fn_ptrs.addy);

test.enable();
```

Leads me to this error

no method named `enable` found for type `()` in the current scope

Odd, shouldn't be doing this. Please help me :)

**Comment by Jascha-N** [comment]
`Hook::create` returns a `Result<Hook>`, not just `Hook`. You have to deal with possible error outcomes.

**Comment by GrahamBest** [comment]
Thanks for the response. I'll take a look 👍

**Comment by GrahamBest** [comment]
Is it possible to cast type std::result::Result to minhook::Hook using the minhook library? I'm stuck. Take this example code:

```
test = unsafe { minhook::Hook::<fn(f32, *mut UserCmd) -> bool>::create::<fn(f32, *mut UserCmd) -> bool>(hook_createmove, fn_ptrs.addy) } as minhook::Hook<fn(f32, *mut UserCmd) -> bool>;
```

As you can see, this is giving me the non-scalar cast problem. Is there a workaround for this? I'm quite stumped.

**Comment by Jascha-N** [comment]
You cannot cast a `Result<T, E>` to `T`. The closest you can do is call `unwrap()` on the result.

These questions are not related to this library. Perhaps you should look at the Rust book or API docs:
https://doc.rust-lang.org/std/result/enum.Result.html
https://doc.rust-lang.org/book/first-edition/error-handling.html#the-result-type
https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html

**Comment by GrahamBest** [comment]
@Jascha-N Thanks for pointing me in the right direction

Here is my code now, for some odd reason it is panicking. I wonder if its because I'm trying to hook a function inside of a game, via dll.

Heres my current code

    

>     let test = unsafe { minhook::Hook::<createmove_fn>::create::<createmove_fn>(hook_createmove, fn_ptrs.addy) };
>     
>     println!("Initializing... 3");
> 
```
>     let test = match test {
>         Ok(ok) => {
>             println!("OKAY! {:?}", ok);
>         },
> 
>         Err(code) => panic!("FAILURE: line 69: test was an {:?}", code)
>     };
```

**Comment by GrahamBest** [comment]
Where createmove_fn is my function pointer type.

**Comment by Jascha-N** [comment]
I can't tell what's wrong, because you didn't give me the error message returned by `Hook::create`. It returns either `Ok(hook)` where `hook: Hook<...>` or Err(error) where `error: Error` which contains a message of what went wrong. It might be a good idea to do something with the error message.

How is the DLL being loaded and where is your code being called? Because you can't just panic if it is called by anything other than Rust code. That would crash the application instead of printing a panic message. Panics should generally be avoided if you are interfacing with code in another language, unless you know what you are doing and use `panic::catch_unwind` from the standard library. Also, if the application/game is not running from a console, there is no place to print any error messages to. You would probably have to use a log file or something like the Windows MessageBox API. Hooking from a DLL is pretty tricky.

So, if you tell me how your code is being called I might be able to help you further. You might also want to have a look at my other project `minject-rs`, which is a DLL injection library for Rust that deals with some of these problems. It is somewhat outdated and lacking in documentation but the API is pretty straightforward and should work just fine.

**Comment by GrahamBest** [comment]
Sorry!! The error message returned was NonExecutable in the panic. I'm just injecting it into the process with an injector I downloaded. I'm calling it via winapis DllMain and also, its not crashing. So I'm not sure exactly what is going on. 

I'll check out minject-rs. Thanks so much!!
